arxiv:
  days: 7
  max_papers: 1
  search_query: "cat:cs.CL"
  sort_by: "lastUpdatedDate"

api:
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model_id: "ep-20241122223516-96dll"
  use_ai: true

output:
  file_path: "output.md"

categories:
  - "model architecture"
  - "multimodal fusion"
  - "modality encoders"
  - "pre-training strategies"
  - "model compression"
  - "distributed training"
  - "evaluation metrics"
  - "correctness verification"
  - "adversarial attacks"
  - "audio features"
  - "audio-text alignment"
  - "audio generation"
  - "cross-domain applications"
  - "transfer learning"
  - "zero-shot and few-shot learning" 
  - "other"