arxiv:
  days: 7
  categories:
    - cs.CL
  max_papers: 1000

api:
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model_id: "ep-20241122223516-96dll"
  use_ai: true

categories:
  - AI
  - NLP
  - CV
  - others

output:
  file_path: "output.md"